before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: keyvault-certdeploy
    ldflags:
      - -s -w -X github.com/emgag/keyvault-certdeploy/internal/lib/version.Version={{.Version}} -X github.com/emgag/keyvault-certdeploy/internal/lib/version.Commit={{.Commit}} -X github.com/emgag/keyvault-certdeploy/internal/lib/version.Date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - files:
      - LICENSE
      - README.md
      - keyvault-certdeploy.yml.dist
checksum:
  name_template: 'checksums.txt'
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
      - keyvault-certdeploy
    image_templates:
#      - "emgag/keyvault-certdeploy:latest"
      - "emgag/keyvault-certdeploy:{{ .Tag }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
